/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.opensearch.trafficgateway.proxy.java-library-conventions")
}

val log4jVersion: String by rootProject.extra

dependencies {
    annotationProcessor("org.apache.logging.log4j:log4j-core:$log4jVersion")

    implementation("com.fasterxml.jackson.core:jackson-databind")
}
